export const LOG_IN_STARTED = 'LOG_IN_STARTED';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';

export const IS_LOG_IN_STARTED = 'IS_LOG_IN_STARTED';
export const IS_LOG_IN_SUCCESS = 'IS_LOG_IN_SUCCESS';
export const IS_LOG_IN_ERROR = 'IS_LOG_IN_ERROR';

export const SIGN_UP_STARTED = 'SIGN_UP_STARTED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_OUT_STARTED = 'SIGN_OUT_STARTED';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const CHANGE_AUTH_PAGE = 'CHANGE_AUTH_PAGE';

export const SEND_CONTACT_STARTED = 'SEND_CONTACT_STARTED';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_ERROR = 'SEND_CONTACT_ERROR';

export const GET_CURRENT_USER_CONTACTS = 'GET_CURRENT_USER_CONTACTS';
export const DELETE_USER_CONTACT = 'DELETE_USER_CONTACT';
export const FILTERED_CONTACT_BY_EMAIL = 'FILTERED_CONTACT_BY_EMAIL';
export const CHANGE_CONTACT_STATUS = 'CHANGE_CONTACT_STATUS';
