export const LOG_IN_STARTED = 'LOG_IN_STARTED';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';

export const IS_LOG_IN_STARTED = 'IS_LOG_IN_STARTED';
export const IS_LOG_IN_SUCCESS = 'IS_LOG_IN_SUCCESS';
export const IS_LOG_IN_ERROR = 'IS_LOG_IN_ERROR';

export const SIGN_UP_STARTED = 'SIGN_UP_STARTED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_OUT_STARTED = 'SIGN_OUT_STARTED';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const CHANGE_AUTH_PAGE = 'CHANGE_AUTH_PAGE';
