
export const CONTACT_STATUS_SWITCHER = 'CONTACT_STATUS_SWITCHER';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const FILTER_CONTACT_STATUS = 'FILTER_CONTACT_STATUS';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';