
export const CONTACT_STATUS_SWITCHER = 'CONTACT_STATUS_SWITCHER';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const FILTER_CONTACT_STATUS = 'FILTER_CONTACT_STATUS';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const LOGIN_USER = 'LOGIN_USER';
export const CREATE_USER = 'CREATE_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
